version: '2'

services:
    mongo-rs:
            container_name: mongo-rs
            image: docker-mongo-local-replicaset:latest
            hostname: mongo-rs
            volumes:
                - ./data/mongo-rs:/data
            user: "${UID_GID}"
            ports:
                - "27017:27017"
                - "27018:27018"
                - "27019:27019"
            networks:
                - common
            restart: always

networks:
    common: